### ISSUE TITLE
Start up

### ISSUE THREAD

**Issue by ghost** [ozimos/Book-A-Meal#55]
What is the command for starting up the backend? I have tried 'npm run start' & 'npm run start:dev'. the CLI shows that the API is listening and the client is working. But am still getting a 404 response when trying to sign up.

**Comment by ozimos** [comment]
To start the app run npm start:dev.  You also need to set up a .env file. I have updated the README to reflect this. A working version of the app is hosted at https://book-a-meal-andela-31.herokuapp.com.
Cheers
